name: Publish Extension

on:
  release:
    types: [created]
  # You can also enable manual workflow runs
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Compile extension
        run: npm run compile
        
      - name: Package extension
        run: npx @vscode/vsce package
        
      - name: Publish to Marketplace
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
        
      - name: Move to releases folder
        run: |
          VERSION=$(node -p "require('./package.json').version")
          mkdir -p releases
          if [ -f "source-code-flattener-$VERSION.vsix" ]; then
            mv source-code-flattener-$VERSION.vsix releases/
            cd releases
            ln -sf source-code-flattener-$VERSION.vsix source-code-flattener-latest.vsix
          else
            echo "VSIX file not found!"
            exit 1
          fi
          
      - name: Commit and push releases
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add releases/
          git commit -m "Update releases for version $(node -p "require('./package.json').version")" || echo "No changes to commit"
          git push
